apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  # The name of the task
  name: deploy-test-app-task
spec:
  params:
    - name: PathToKustomize
      description: path to the kustomize directory
      default: /workspace/git/manifests
  resources:
    inputs:
    - name: image
      type: image
    - name: git
      type: git
      # The output resource(s) of the task, such as an image built from the source code
  steps:
    - name: kubectl
      image: gcr.io/cloud-builders/kubectl
      args:
      - "apply"
      - "-k"
      - "$(params.PathToKustomize)"