apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tekton-ingress-resource
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: github-listener-interceptor
              servicePort: 8080